pipeline:
  scp:
    image: appleboy/drone-scp
    pull: true
    host: 
      - 139.162.9.68
    port: 22
    username: root
    user: root
    secrets: [ ssh_password ]
    target: /root
    source:
      - /drone/src/github.com/reactgrils/stream-dashboard
    when:
      branch: master

  ssh:
    image: appleboy/drone-ssh
    host: 
      - 139.162.9.68
    username: root
    user: root
    secrets: [ ssh_password ]
    command_timeout: 600
    script:
      - . /root/.nvm/nvm.sh && nvm use 10.9.0
      - mkdir -p /var/www/html/stream-dashboard.tomas.website
      - cp -a ./* /var/www/html/stream-dashboard.tomas.website
      - cd /root/drone/src/github.com/reactgrils/stream-dashboard
      - yarn install
      - sudo kill $(sudo lsof -t -i:12002)
      - yarn deploy
      - cd /root
      - rm -rf /root/drone
    when:
      branch: master
